# Generated by Django 2.1.5 on 2019-01-21 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20190121_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='bethrooms',
            new_name='bathrooms',
        ),
    ]
