# Generated by Django 2.1.5 on 2019-01-21 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20190121_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='Price',
            new_name='price',
        ),
    ]
